apps/sre/web/router.ex
defmodule Sre.Router do
  use Sre.Web, :router
  use Plug.ErrorHandler
  use Phoenix.Router

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  alias Plug.Conn

  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    conn_data = conn
      |> Conn.fetch_cookies()
      |> Conn.fetch_query_params()
      |> Conn.fetch_session()

    conn_data = %{
      "request" => %{
        "cookies" => conn_data.req_cookies,
        "url" => "#{conn_data.scheme}://#{conn_data.host}:#{conn_data.port}#{conn_data.request_path}",
        "user_ip" => (conn_data.remote_ip |> Tuple.to_list() |> Enum.join(".")),
        "headers" => Enum.into(conn_data.req_headers, %{}),
        "session" => conn_data.private[:plug_session] || %{},
        "params" => conn_data.params,
        "method" => conn_data.method
      },
      "server" => %{
        "pid" => System.get_env("MY_SERVER_PID"),
        "host" => "#{System.get_env("MY_HOSTNAME")}:#{System.get_env("MY_PORT")}",
        "root" => System.get_env("MY_APPLICATION_PATH")
      }
    }

    Rollbax.report(kind, reason, stacktrace, %{}, conn_data)
  end

  pipeline :browser do
    plug Sre.Plugs.EnforceDomain
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug PlugForwardedPeer
    plug User.Auth
    plug Sre.UserIp
  end

  pipeline :csrf do
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ui_guide_layout do
    plug :put_layout, {Sre.LayoutView, :ui_guide}
  end

  pipeline :non_prod do
    plug Sre.Plugs.EnvironmentWhitelist, [:dev, :qa]
  end

  scope "/", Sre do
    pipe_through [:browser]

    get "/",        PageController, :index
    get "/terms",   PageController, :terms
    get "/privacy", PageController, :privacy
    get "/about",   PageController, :about
    get "/solution",   PageController, :solution
    get "/homebuyer",   PageController, :solution
    get "/contact", PageController, :contact
    get "/sell",    PageController, :selling
    get "/careers",    PageController, :careers
    get "/agency",  PageController, :agency
    get "/savings", PageController, :savings
    get "/testimonials", PageController, :testimonials
    get "/home-mortgage-rate-calculator", PageController, :home_mortgage_rate_calculator
    get "/mortgage", PageController, :mortgage
    get "/platform", PageController, :platform
    get "/partners", PageController, :partners
    get "/rewards", PageController, :careers
    post "/rewards", PageController, :send_rewards_message

    # Property pages
    get "/properties", PropertyController, :index
    get "/properties/:url", PropertyController, :details

    get  "/update_password", UserManagement.PasswordController, :reset_password
    post "/update_password", UserManagement.PasswordController, :request_reset

    get  "/change_password", UserManagement.PasswordController, :edit
    put  "/change_password", UserManagement.PasswordController, :update

    get "/verify_account/:token", Registration, :verify

    get "/invite", SessionController, :invite
    get "/login",  SessionController, :new
    get "/logout", AuthController, :delete
    get "/sitemap.xml", PageController, :sitemap

    get "/500", PageController, :error_500
    get "/404", PageController, :error_404
  end

  scope "/api/v1", Sre do
    pipe_through :api

    scope "/listings" do
      pipe_through [:non_prod]
      get "/", PropertyApiController, :index
      get "/:id", PropertyApiController, :show
    end

    scope "/users" do
      pipe_through :api
    end
  end

  scope "/mysre", Sre.UserManagement, as: :user_management do
    pipe_through :browser
    get "/", PageController, :index
    get "/favorites", GroupController, :index
    get "/edit-profile", UserController, :edit
    put "/edit-profile/:user_id", UserController, :update
    put "/edit-profile/:user_id/change_password", PasswordController, :update
    get "/edit-profile/:user_id/email/edit", EmailController, :edit
    put "/edit-profile/:user_id/email", EmailController, :update
    get "/saved-search", SavedSearchController, :index
    delete "/saved-search/:id", SavedSearchController, :delete
    get "/verify-email/:user_id/email", EmailController, :verify
    post "/change_password", PasswordController, :auth_0_update

    get "/agent-suggestions", SuggestionController, :index
  end

  scope "/auth", Sre do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/ui-kit", Sre do
    pipe_through [:non_prod, :browser, :csrf, :ui_guide_layout]
    get "/", UIStyleGuideController, :index
    get "/colors", UIStyleGuideController, :colors
    get "/typography", UIStyleGuideController, :typography
    get "/icons", UIStyleGuideController, :icons
    get "/buttons", UIStyleGuideController, :buttons
    get "/form-elements", UIStyleGuideController, :form_elements
    get "/content-types", UIStyleGuideController, :content_types
    get "/notification", UIStyleGuideController, :notification
    get "/location-components", UIStyleGuideController, :location_components
  end

end

apps/sre/lib/service/user/user_by_token.ex
defmodule Sre.UserByToken do

  @moduledoc """
  Service that handles - capturing the user
  record via the token - and updating email_verified flag.
  """

  use Ecto.Schema
  import Ecto.Changeset, only: [cast: 3, put_change: 3]

  alias Schema.Repo

  schema "users" do
    field :anonymous_id, Ecto.UUID
    field :email_verified, :boolean
  end

  def mark_email_as_verified(token) do
    __MODULE__
    |> Repo.get_by(anonymous_id: token)
    |> case do
      nil -> nil
      record -> update(record)
    end
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email_verified])
  end

  defp update(record) do
    record
    |> changeset
    |> put_change(:email_verified, true)
    |> Repo.update!
  end

end

apps/sre/lib/service/user/user_suggestion.ex
defmodule Sre.UserSuggestion do
  @moduledoc """
    Handle fetching the User agent suggestions.
  """

  import Ecto.Query, only: [from: 2]

  alias Schema.{Repo, Resource.Listing}

  def fetch(user_id) do
      user_id
      |> suggestions_query
      |> Repo.all
  end

  defp suggestions_query(user_id) do
    from i in Listing,
      join: g in assoc(i, :groups),
      where: g.user_id == ^user_id and g.name != "Favorites" and g.created_by != ^user_id,
      preload: [:photos]
  end
end

apps/sre/lib/sre/user/view_helper.ex
defmodule Sre.User.ViewHelper do
  def get_current_user_first_name(nil), do: ""
  def get_current_user_first_name(user) do
    user.first_name || ""
  end

  def get_current_user_last_name(nil), do: ""
  def get_current_user_last_name(user) do
    user.last_name || ""
  end

  def get_current_user_email(nil), do: ""
  def get_current_user_email(user) do
    user.email || ""
  end

  def get_current_user_phone(nil), do: ""
  def get_current_user_phone(%{user_phones: []}), do: ""
  def get_current_user_phone(%{user_phones: [phone | _tail] = phones}) when is_list(phones) do
    phone.phone_number
  end
  def get_current_user_phone(_user), do: ""
end

apps/sre/web/controllers/user_management/email_controller.ex
defmodule Sre.UserManagement.EmailController do
  use Sre.Web, :controller

  use Sre.Controller

  plug Sre.RequireLogin when action in [:edit, :update]

  alias Schema.{Repo, Resource.User}
  alias Sre.Service.Email.Delivery
  alias Sre.Tokenizer

  def edit(conn, %{"user_id" => _user_id}, user) do
    render conn, "edit_email.html", changeset: User.changeset(user)
  end

  def update(conn, %{"email" => email}, user) do
    Delivery.send_verify_email(user, email, conn)
    render conn, "email_submitted.html"
  end

  def verify(conn, %{"token" => token, "requested_email" => email}, _) do
    case Tokenizer.fetch_and_validate(token) do
      {:valid, user} ->
        user
        |> User.changeset(%{email: email})
        |> Repo.update
        render conn, "verified.html", message: true
      {:expired, _user} ->
        conn
        |> put_flash(:info, "Your email verify link expired.")
        render conn, "verified.html", message: false
    end
  end

end

apps/sre/web/controllers/user_management/group_controller.ex
defmodule Sre.UserManagement.GroupController do

  use Sre.Web, :controller
  use Sre.Controller

  plug Sre.RequireLogin

  alias Group.ListingService, as: Api

  def index(conn, _params, user) do
    favorites = Api.fetch_by_user_id_and_name(user.id, "Favorites")
    conn
    |> render("index.html", [favorites: favorites])
  end
end

apps/sre/web/controllers/user_management/page_controller.ex
defmodule Sre.UserManagement.PageController do
  use Sre.Web, :controller

  plug Sre.RequireLogin

  def index(conn, _params) do
    redirect(conn, to: user_management_user_path(conn, :edit))
  end
end

apps/sre/web/controllers/user_management/password_controller.ex
defmodule Sre.UserManagement.PasswordController do
  use Sre.Web, :controller

  alias User.{PasswordToken, PasswordChange}
  alias Sre.Service.Email.Composer
  alias Sre.Router.Helpers

  def auth_0_update(%Plug.Conn{assigns: %{current_user: user}} = conn, params) do
    changeset =
      PasswordChange.password_changeset(params["password_change"])
    if changeset.valid? do
      case PasswordChange.update_auth0(user, params) do
        {:ok, :updated} ->
          response(conn, user)
        _ ->
          conn
          |> put_flash(:info, "Unable to update password")
          |> response(user)
      end
    else
      conn
      |> put_flash(:info, "Unable to update password")
      |> response(user, changeset)
    end
  end

  defp response(conn, user, changeset \\ PasswordChange.password_changeset(%{})) do
    redirect conn,
      to: user_management_user_path(conn, :edit),
      password_changeset: changeset,
      user_id: user.id
  end

  # GET /update_password
  # This presents a form with enter email input.
  def reset_password(conn, %{"action" => "forgot_password"}) do
    do_reset_password(conn, "forgot_password")
  end

  # GET /update_password
  # This is button that gets clicked. Simply generates the email.
  def reset_password(conn, %{"action" => "change_password"}) do
    do_reset_password(conn, "change_password")
  end

  def reset_password(conn, _) do
    do_reset_password(conn, "forgot_password")
  end

  defp do_reset_password(%{assigns: %{current_user: nil}} = conn, action) do
    conn
    |> assign(:action, String.to_atom(action))
    |> render("forgot_password.html")
  end

  defp do_reset_password(%{assigns: %{current_user: user}} = conn, _action) do
    do_request_reset(conn, user, "change_password.html")
  end

  # POST /update_password
  def request_reset(conn, %{"email_address"=> email}) do
    do_request_reset(conn, email, "thank_you.html")
  end

  defp do_request_reset(conn, param, email_template) do
    user = param
    |> PasswordToken.set_reset_password_token
    url = reset_password_url(conn, user)
    user
    |> Composer.send_reset_password_email(url)
    |> case do
      {:success, _email} ->
        # @todo: Send email confirmation here
        # We sent a reset link...content
        render conn, email_template
      {:failure, :not_on_file} ->
        conn
        |> put_flash(:info, "No account associated with that email")
        |> render(email_template)
      {:failure, _, _} ->
        # We sent a reset link...content
        render conn, email_template
    end
  end

  defp reset_password_url(conn, user) do
    Helpers.password_path(conn, :edit, %{user_id: user.id, token: user.forgot_password_token, email: user.email})
  end

  # GET /Present User Form.
  def edit(conn, %{"token" => token, "email" => email}) do
    token
    |> PasswordToken.fetch_and_validate(email)
    |> case do
      {:valid, user} ->
        conn
        |> assign(:user, user)
        |> render("update_password_form.html")
      {:expired, _user} ->
        expired_link(conn)
    end
  end

  def update(conn, %{"token" => token, "email" => email} = params) do
    token
    |> PasswordToken.fetch_and_validate(email)
    |> case do
      {:valid, user} ->
        PasswordToken.update_auth0_password(user, params)
        # case logged in - log out user and redirect to login with new password.
        render conn, "thank_you.html", message: "You will be relogged in."
      {:expired, _} ->
        expired_link(conn)
    end
  end

  defp expired_link(conn) do
    conn
    |> put_flash(:info, "Your Link has expired")
    |> redirect(to: password_path(conn, :reset_password), action: "forgot_password")
  end

end

apps/sre/web/controllers/user_management/saved_search_controller.ex
defmodule Sre.UserManagement.SavedSearchController do
  use Sre.Web, :controller

  alias User.Search
  alias Poison.Parser

  def index(conn, _params) do
    searches =
      conn.assigns.current_user.id
      |> Search.get_searches_by_user_id
      |> Enum.map(fn(%{search_attributes: attrs} = search) ->
          attrs =
            attrs
            |> Enum.map(&decode_values/1)

          %{search | search_attributes: attrs}
         end)
    conn
    |> render("index.html", searches: searches)
  end

  def delete(conn, %{"id" => saved_search_id}) do
    conn.assigns.current_user.id
    |> Search.delete_search(saved_search_id)

    conn
    |> redirect(to: user_management_saved_search_path(conn, :index))
  end

  def decode_values(%{attribute_key: key, attribute_values: value} = attrs) do
    key = parse(key)
    value = parse(value)

    %{attrs | attribute_key: key, attribute_values: value}
  end

  defp parse(value) do
    case Parser.parse value do
      {:ok, result} -> result
      {:error, _} -> ""
    end
  end

end

apps/sre/web/controllers/user_management/suggestion_controller.ex
defmodule Sre.UserManagement.SuggestionController do
  use Sre.Web, :controller
  use Sre.Controller

  plug Sre.RequireLogin

  alias Sre.UserSuggestion

  def index(conn, _, user) do
    suggestions = UserSuggestion.fetch(user.id)
    conn
    |> assign(:suggestions, suggestions)
    |> render(:index)
  end

end

apps/sre/web/controllers/user_management/user_controller.ex
defmodule Sre.UserManagement.UserController do

  use Sre.Web, :controller
  use Sre.Controller

  plug Sre.RequireLogin
  alias Ecto.Changeset
  alias User.{Management, PasswordChange, Query}
  alias Schema.{
    Resource.User,
    Resource.UserPhone,
    Repo
  }

  def edit(conn, _, user) do
    user = Repo.preload(user, [:user_profile, user_phones: Query.user_phones_preload_query(user)])

    changeset =
      user
      |> User.changeset
      |> Changeset.put_assoc(:user_phones, user_phones(user.user_phones))

    render conn, "edit.html",
      changeset: changeset,
      password_changeset: PasswordChange.password_changeset(%{}),
      user_id: user.id
  end

  def update(conn, params, user) do
    with {:ok, user}     <- Management.update(user, params["user"]),
         {:ok, _profile} <- Management.update_profile(user, params["user"]["user_profile"])
    do
      case user.requested_email do
        true ->
          conn
          |> put_flash(:notice, "We sent a verification email to the email requested.")
          |> response(user)
        _ ->
          response(conn, user)
      end
    else
      {:error, _} ->
        conn
        |> put_flash(:error, "Unable to update user profile")
        |> redirect(to: user_management_user_path(conn, :edit))

      :error -> redirect conn, to: user_management_user_path(conn, :edit)
    end
  end

  defp response(conn, user) do
    redirect conn, to: user_management_user_path(conn, :edit),
        changeset: User.changeset(user, %{}), user_id: user.id
  end

  defp user_phones([]) do
    [%UserPhone{} |> UserPhone.changeset]
  end

  defp user_phones(phones) do
    phones
    |> Enum.map(fn phone ->
        UserPhone.changeset(phone)
       end)
  end

end

apps/sre/web/views/user_management/email_view.ex
defmodule Sre.UserManagement.EmailView do
  use Sre.Web, :view
end

apps/sre/web/views/user_management/group_view.ex
defmodule Sre.UserManagement.GroupView do
  use Sre.Web, :view

end

apps/sre/web/views/user_management/password_view.ex
defmodule Sre.UserManagement.PasswordView do
  use Sre.Web, :view

  def update_password_url(user) do
    "/mysre/edit-profile/#{user.id}/change_password?token=" <>
      "#{user.forgot_password_token}&email=#{user.email}"
  end
end

apps/sre/web/views/user_management/saved_search_view.ex
defmodule Sre.UserManagement.SavedSearchView do
  use Sre.Web, :view

  def encode_search_attributes(attrs) do
    attrs
    |> attributes_to_map
    |> attributes_map_to_query_params
  end

  def attributes_to_map([]), do: %{}
  def attributes_to_map(attrs) do
    attrs
    |> Enum.reduce(%{}, fn(%{attribute_key: key, attribute_values: value}, acc) ->
        acc
        |> Map.put(key, value)
       end)
  end

  def attributes_map_to_query_params(map) when map == %{}, do: ""
  def attributes_map_to_query_params(attrs_map) do
    attrs_map
    |> URI.encode_query
  end
end

apps/sre/web/views/user_management/suggestion_view.ex
defmodule Sre.UserManagement.SuggestionView do
  use Sre.Web, :view

end

apps/sre/web/views/user_management/user_view.ex
defmodule Sre.UserManagement.UserView do
  use Sre.Web, :view
end

apps/sre/web/templates/user_management/user/edit.html.eex
<p style="color:red;text-align:center;margin-top:20px;" role="alert"><%= get_flash(@conn, :error) %></p>

<div class="user-page">
  <%= render Sre.UserManagement.UserView, "nav.html" %>
  <section class="user-page__main">
    <h1 class="user-page__main__section-header">
      Your Profile
    </h1>
    <%= form_for @changeset, user_management_user_path(@conn, :update, @user_id), fn f -> %>
      <div class="grid u-flex-align-items-center u-mbottom16">
        <div class="grid__sm--12 grid__md--3 user-page__form-label">
          <label class="strong u-font14 u-line14 u-text-gray-600" for="fname">First Name</label>
        </div>
        <div class="grid__sm--12 grid__md--9">
          <%= text_input(f, :first_name, class: "input input-scaffold__input input--text input--md" ) %>
        </div>
      </div>
      <div class="grid u-flex-align-items-center u-mbottom16">
        <div class="grid__sm--12 grid__md--3 user-page__form-label">
          <label class="strong u-font14 u-line14 u-text-gray-600" for="lname">Last Name</label>
        </div>
        <div class="grid__sm--12 grid__md--9">
          <%= text_input(f, :last_name, class: "input input-scaffold__input input--text input--md" ) %>
        </div>
      </div>

      <div class="grid u-flex-align-items-center u-mbottom16">
        <div class="grid__sm--12 grid__md--3 user-page__form-label">
          <label class="strong u-font14 u-line14 u-text-gray-600" for="email">Email Address</label>
        </div>
        <div class="grid__sm--12 grid__md--9">
          <%= text_input(f, :email, class: "input input-scaffold__input input--text input--md") %>
        </div>
      </div>

      <%= inputs_for f, :user_phones, fn p -> %>
        <div class="grid u-flex-align-items-center u-mbottom16">
          <div class="grid__sm--12 grid__md--3 user-page__form-label">
            <label class="strong u-font14 u-line14 u-text-gray-600" for="phone_number">Phone Number</label>
          </div>
          <div class="grid__sm--12 grid__md--9">
            <%= text_input(p, :phone_number, class: "input input-scaffold__input input--text input--md") %>
          </div>
        </div>

        <div class="grid u-flex-align-items-center u-mbottom16">
          <div class="grid__sm--12 grid__md--3 user-page__form-label">
            <label class="strong u-font14 u-line14 u-text-gray-600" for="phone_extension">Phone Ext.</label>
          </div>
          <div class="grid__sm--12 grid__md--9">
            <%= text_input(p, :phone_extension, class: "input input-scaffold__input input--text input--md") %>
          </div>
        </div>
      <% end %>

      <%= inputs_for f, :user_profile, fn p -> %>
        <div class="grid u-flex-align-items-start u-mbottom16">
          <div class="grid__sm--12 grid__md--3 user-page__form-label">
            <label class="strong u-font14 u-line14 u-text-gray-600" for="street">Address</label>
          </div>
          <div class="grid__sm--12 grid__md--9">
            <%= text_input(p, :address, class: "input input-scaffold__input input--text input--md u-mbottom16", placeholder: "Street Address" ) %>
            <div class="grid">
              <div class="grid__sm--6">
                <%= text_input(p, :city,
                  class: "input input-scaffold__input input--text input--md",
                  placeholder: "City" ) %>
              </div>
              <div class="grid__sm--2">
                <%= text_input(p, :state,
                  class: "input input-scaffold__input input--text input--md",
                  placeholder: "State" ) %>
              </div>
              <div class="grid__sm--4">
                <%= text_input(p, :zip,
                  class: "input input-scaffold__input input--text input--md",
                  placeholder: "Zipcode" ) %>
              </div>
            </div>
          </div>
        </div>
        <div class="u-text-right">
          <%= Sre.UI.Button.ButtonDefault.render_template(
            value: "Update Profile",
            classname: "button--primary",
          )%>
        </div>
      <% end %>
    <% end %>
    <h2 class="user-page__main__section-header u-mtop32">
      Your Password
    </h2>

    <%= form_for @password_changeset, user_management_password_path(@conn, :auth_0_update), fn f ->  %>
      <div class="grid u-flex-align-items-center u-mbottom16">
        <div class="grid__sm--12 grid__md--3 user-page__form-label">
          <label class="strong u-font14 u-line14 u-text-gray-600" for="fname">Current Password</label>
        </div>
        <div class="grid__sm--12 grid__md--9">
          <%= password_input(f, :current,
            class: "input input-scaffold__input input--text input--md",
            placeholder: "Current Password" ) %>
        </div>
      </div>
      <div class="grid u-flex-align-items-center u-mbottom16">
        <div class="grid__sm--12 grid__md--3 user-page__form-label">
          <label class="strong u-font14 u-line14 u-text-gray-600" for="fname">New Password</label>
        </div>
        <div class="grid__sm--12 grid__md--9">
          <%= password_input(f, :password,
            class: "input input-scaffold__input input--text input--md",
            placeholder: "New Password" ) %>
        </div>
      </div>
      <div class="grid u-flex-align-items-center u-mbottom16">
        <div class="grid__sm--12 grid__md--3 user-page__form-label">
          <label class="strong u-font14 u-line14 u-text-gray-600" for="fname">Confirm Password</label>
        </div>
        <div class="grid__sm--12 grid__md--9">
          <%= password_input(f, :password_confirmation,
            class: "input input-scaffold__input input--text input--md",
            placeholder: "Confirm Password" ) %>
        </div>
      </div>
      <div class="u-text-right">
        <%= Sre.UI.Button.ButtonDefault.render_template(
          value: "Update Password",
          classname: "button--primary",
        )%>
      </div>
    <% end %>
  </section>
</div>

apps/sre/web/templates/user_management/user/nav.html.eex
<nav class="user-page__nav">
    <ul class="user-page__nav__menu">
        <li class="user-page__nav__menu__item">
        <%= link(
            "Your Profile",
            to: "/mysre/edit-profile",
            class: "user-page__nav__menu__link"
        )%>
        </li>
        <li class="user-page__nav__menu__item">
        <%= link(
            "Favorites",
            to: "/mysre/favorites",
            class: "user-page__nav__menu__link"
        )%>
        </li>
        <li class="user-page__nav__menu__item">
        <%= link(
            "Saved Searches",
            to: "/mysre/saved-search",
            class: "user-page__nav__menu__link"
        )%>
        </li>
        <li class="user-page__nav__menu__item">
        <%= link(
            "Agent Suggestions",
            to: "/mysre/agent-suggestions",
            class: "user-page__nav__menu__link"
        )%>
        </li>
    </ul>
</nav>